# -*- coding: utf-8 -*-
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1povSi66R74SDmsbsAbsxFgu0giSeOEXB
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

data = np.array([30,31,32,33,34,35,36,37,38,39])

X = []
y = []

for i in range(len(data)-3):
    X.append(data[i:i+3])
    y.append(data[i+3])

X = np.array(X)
y = np.array(y)

X = X.reshape((X.shape[0], X.shape[1], 1))

model = Sequential()
model.add(SimpleRNN(10, activation='tanh', input_shape=(3,1)))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')

model.fit(X, y, epochs=200, verbose=0)

predicted = model.predict(X)

plt.plot(y, label="Actual Temperature")
plt.plot(predicted, label="Predicted Temperature")

plt.title("RNN Temperature Prediction")
plt.xlabel("Days")
plt.ylabel("Temperature")
plt.legend()

plt.show()

